### ISSUE TITLE
Import error libopenjp2.so.7

### ISSUE THREAD

**Issue by Padraig76** [irahorecka/comics#1]
I am trying to use this package but I am running into this error:
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory

My setup:
Raspberry 3 Mod. b
Raspian GNU/linux 11 (bullseye)
Python 3.9.2 in virtual environment

Thank you for the support!

**Comment by irahorecka** [comment]
Hello, it appears that this is a common issue on Raspian. Have you tried installing `libopenjp2-7`?

```bash
sudo apt-get install libopenjp2-7
```

**Comment by Padraig76** [comment]
Hi! Thank you for the quick reply. Yes, I did try that, but not using apt-get because I was trying to avoid installing it globally. I just wanted it in the virtual environment so I used pip. Just tried again for the sake of knowing the result and yes, using apt-get it installs globally, but no, the initial error persists: I can't install it using pip in my virtual environment. I receive:
_Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement libopenjp2-7
ERROR: No matching distribution found for libopenjp2-7_

Apt-get was successful using: 
_http://mirror.pyratelan.org/raspbian/raspbian bullseye/main armhf libopenjp2-7 armhf 2.4.0-3_

Any idea (without me trying to install the missing piece manually)?

**Comment by irahorecka** [comment]
I'm unfortunately don't have an idea at the moment; unfortunately, this appears to be a `Pillow` issue. Could you try pip installing Pillow on its own and see if the issue arises? I have a Raspberry Pi 3B+ with Python 3.7.3 installed and installing Pillow works fine.

**Comment by Padraig76** [comment]
I removed libopenjp2-7 again and checked that Pillow is installed in the venv. It is, version 9.4.0. Yet the error is back again. 
Maybe it's the version of Pillow? Which one are you running?

**Comment by irahorecka** [comment]
Yes, I have Pillow v9.4.0 installed on my Raspberry Pi virtual environment.

**Comment by Padraig76** [comment]
What exactly do you mean by "start anew"? Build a new venv and see if it is running there?

**Comment by irahorecka** [comment]
Yes that sounds like a good idea

**Comment by Padraig76** [comment]
What I have done:
Installed in a venv on my Windows10 machine (my daily driver): Without any further steps it worked.
Installed it in a venv on my Raspberry3: Same error.
Installed it outside a venv on my Raspberry3: Same error.
Installed libopenjp2-7 globally on the Raspberry3: Both previous setups on the raspberry worked. But:
In the venv neither download nor show worked.
Outside the venv download worked, show didn't. But I guess show doesn't work because I am running the Raspberry headless, so it may be a challenge of the way I log into the machine.
Any clue left to share? Otherwise you may close the issue because I do share your asumption that it is not an issue of `comics`...

**Comment by Padraig76** [comment]
And we have a winner! Installing this [package](https://pypi.org/project/pylibjpeg-openjpeg/) did the trick. Download now works, the error is gone. Show still doesn't, but I'll leave that for someone else to solve. ;-)
Thank you!
P.S.: Is there any chance you'll include XKCD (comics)?

**Comment by irahorecka** [comment]
That's wonderful to hear - glad it solved your issue. I was also curious about XKCD, but it seems that GoComics doesn't have XKCD ([link](https://www.gocomics.com/search/results?utf8=%E2%9C%93&terms=xkcd)). I'll close this issue.
