### ISSUE TITLE
Support: Get absolute png url address?

### ISSUE THREAD

**Issue by lexterror** [irahorecka/comics#2]
Hi I would like to get the absolute png url address to be able to share/embed the comic using url only.

Thank you!

**Comment by lexterror** [comment]
_comic_strip_url

*return date error

**Comment by lexterror** [comment]
got it! Thank you!

**Comment by irahorecka** [comment]
Actually this is a good issue! I'll modify `_comic_strip_url` to be a public attribute.

**Comment by irahorecka** [comment]
Addressed in commit 7af1c4e
